---

- hosts: all
  become: true
  tasks:

  - name: install packages on Ubuntu (apache, php)
    apt:
      name: 
        - apache2 
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install packages on CentOS (apache, php)
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
