---

- hosts: all
  become: true
  tasks:

  - name: update repo index (Debian)
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: remove apache2 package (Debian)
    apt:
      name: apache2
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: remove php support for apache (Debian)
    apt:
      name: libapache2-mod-php
      state: absent
    when: ansible_distribution == "Ubuntu"


  - name: update repo index
    dnf:
      update_cache: yes

  - name: repo update (CentOS)
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: remove apache2 package (CentOS)
    dnf:
      name: httpd
      state: absent
    when: ansible_distribution == "CentOS"

  - name: remove php (CentOS)
    dnf:
      name: php
      state: absent
    when: ansible_distribution == "CentOS"
