---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    dnf:
      update: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:

  - name: install packages on Ubuntu (apache, php)
    tags: apache, apache2, ubuntu
    apt:
      name: 
        - apache2 
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install packages on CentOS (apache, php)
    tags: apache, httpd, centos
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"


- hosts: db_servers
  become: true
  tasks:

  - name: install mariaDB package (CentOS)
    tags: centos, db, mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariaDB package (Ubuntu)
    tags: ubuntu, db, mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
